const parse = require('../src/index.js');
const snippets = require('./snippets');

// console.log('withMultipleMessages');
// console.log(parse(snippets.withMultipleMessages));
// console.log('withExpressionMessage');
// console.log(parse(snippets.withExpressionMessage));
// console.log('withLiteralMessage');
// console.log(parse(snippets.withLiteralMessage));
// console.log('withCommentAndExpression');
// console.log(parse(snippets.withCommentAndExpression));
// console.log('withCommentAndLiteral');
// console.log(parse(snippets.withCommentAndLiteral));
// console.log('withMultipleExpressions');
// console.log(parse(snippets.withMultipleExpressions));
console.log('withAttributes');
console.log(parse(snippets.withAttributes));
console.log('withVariables');
console.log(parse(snippets.withVariables));
console.log('withElements');
console.log(parse(snippets.withElements));
// console.log('withDecoratorAndImport');
// console.log(parse(snippets.withDecoratorAndImport));
console.log('withDuplicateMessageIds');
console.log('finally', parse(snippets.withDuplicateMessageIds));
